# Generated by Django 5.0.2 on 2024-06-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oura_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
